---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-airflow
  namespace: airflow
spec:
  storageClassName: postgres-airflow-sc
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
