apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./10-postgres-airflow-sc.yaml
  - ./20-postgres-airflow-pvc.yaml

helmCharts:
  - name: postgresql
    releaseName: postgres-airflow
    version: 14.2.3
    repo: https://charts.bitnami.com/bitnami

    valuesInline:

      ## @section PostgreSQL Primary parameters
      ##
      primary:
        ## PostgreSQL Primary persistence configuration
        ##
        persistence:
          ## @param primary.persistence.enabled Enable PostgreSQL Primary data persistence using PVC
          ##
          enabled: true
          ## @param primary.persistence.existingClaim Name of an existing PVC to use
          ##
          existingClaim: postgres-airflow

        ## pgHbaConfiguration: |-
        ##   local all all trust
        ##   host all all localhost trust
        ##   host mydatabase mysuser 192.168.0.0/24 md5
        pgHbaConfiguration: |-
          local all all trust
          host all all 0.0.0.0/0 trust
          hostnossl all all 0.0.0.0/0 trust
