apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pihole
  namespace: pihole
  labels:
    app: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  serviceName: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      hostNetwork: true
      dnsPolicy: 'None'
      dnsConfig:
        nameservers:
          # upstream DNS used by pihole.
          - 1.1.1.1
          - 1.0.0.1
      # Assign IP address to the device name.
      hostAliases:
        - ip: 192.168.1.69
          hostnames: [duet-mac]
        - ip: 192.168.1.70
          hostnames: [duet-iphone]
        - ip: 192.168.1.10
          hostnames: [dqsmart]
        - ip: 192.168.1.110
          hostnames: [duet-ubuntu]
        - ip: 192.168.1.137
          hostnames: [nini-iphone]
        - ip: 192.168.1.200
          hostnames: [bosch-dishwasher]
        - ip: 192.168.1.201
          hostnames: [lg-smart-dryer]
        - ip: 192.168.1.202
          hostnames: [lg-washing-machine]
        - ip: 192.168.1.203
          hostnames: [duet-samsung-tv]
        - ip: 192.168.1.204
          hostnames: [duet-camera]
        - ip: 192.168.1.205
          hostnames: [dyson-formaldehyde-purifier]
        - ip: 192.168.1.206
          hostnames: [alexa-echo-dot]
      containers:
        - name: pihole
          # https://hub.docker.com/r/pihole/pihole/tags
          image: pihole/pihole:2024.02.2
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: 'Asia/Ho_Chi_Minh'
            - name: WEBPASSWORD
              value: '123123'
            - name: FTLCONF_LOCAL_IPV4
              value: 192.168.1.110
            - name: FTLCONF_BLOCK_ICLOUD_PR
              value: 'false'
          securityContext:
            privileged: true
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
            - containerPort: 67
              protocol: UDP
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: pihole-etc
              mountPath: /etc/pihole
            - name: pihole-dnsmasq
              mountPath: /etc/dnsmasq.d
          resources:
            requests:
            limits:
              memory: 1Gi
              cpu: 1
      volumes:
        - name: pihole-etc
          persistentVolumeClaim:
            claimName: pihole-etc
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq
