---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow
  namespace: airflow
spec:
  storageClassName: airflow-sc
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
