apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./10-airflow-sc.yaml
  - ./20-airflow-pvc.yaml
  - ./30-airflow-secret.yaml

helmCharts:
  - name: airflow
    releaseName: airflow
    version: 1.12.0
    repo: https://airflow.apache.org

    valuesFile: values.yaml
