config:
  webserver:
    expose_config: 'True'

secret:
  - envName: POSTGRES_PASSWORD
    secretName: postgres-airflow-postgresql
    secretKey: postgres-password

postgresql:
  enabled: false

fernetKeySecretName: airflow-metadata
webserverSecretKeySecretName: airflow-metadata

data:
  metadataSecretName: airflow-metadata

triggerer:
  enabled: false

# Enable RBAC (default on most clusters these days)
rbac:
  create: false

# Airflow executor
# One of: LocalExecutor, LocalKubernetesExecutor, CeleryExecutor, KubernetesExecutor, CeleryKubernetesExecutor
executor: "KubernetesExecutor"

webserver:
  # Create initial user.
  defaultUser:
    enabled: true
    role: Admin
    username: duyet
    email: me@duyet.net
    firstName: Duyet
    lastName: Le
    password: "123123"

  # Access: http://duet-ubuntu:30000
  service:
    type: NodePort
    annotations:
      tailscale.com/expose: "true"
      tailscale.com/hostname: "airflow"
      tailscale.com/tags: "tag:k8s,tag:minipc,tag:duet-ubuntu"
    #ports:
    #  - name: airflow-ui
    #    port: 8080
    #    targetPort: 8080
    #    nodePort: 30000

workers:
  persistence:
    enabled: false

dags:
  persistence:
    enabled: true

    # 20-airflow-pvc.yaml
    existingClaim: airflow

    # TODO: Git sync

logs:
  persistence:
    enabled: true
    size: 10Gi
