apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
helmCharts:
  - name: tailscale-operator
    includeCRDs: true
    releaseName: tailscale-operator
    version: 1.61.11
    repo: https://pkgs.tailscale.com/helmcharts

    valuesInline:
      operatorConfig:
        defaultTags:
          - 'tag:k8s-operator'
      proxyConfig:
        defaultTags: 'tag:k8s,tag:duet-ubuntu,tag:minipc'

resources:
  - ./tailscale-secret.yaml
