---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: home-assistant-sc
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /media/duyet/Data/k8s-data/home-assistant
volumeBindingMode: WaitForFirstConsumer
