---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
spec:
  storageClassName: home-assistant-sc
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
