---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  type: NodePort
  ports:
  - port: 8123
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30123
