apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - ./10-namespace.yaml
  - ./20-home-assistant-sc.yaml
  - ./30-pvc.yaml
  - ./40-deployment.yaml
  - ./50-service.yaml

commonLabels:
  app.kubernetes.io/name: home-assistant
  app: home-assistant
