apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: scheduling-restart
    includeCRDs: true
    releaseName: scheduling-restart
    version: 0.1.0
    repo: https://duyet.github.io/charts
    valuesFile: values.yaml
