apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: altinity-clickhouse-operator 
    includeCRDs: true
    releaseName: clickhouse-operator
    version: 0.24.0
    repo: https://docs.altinity.com/clickhouse-operator/

    valuesInline:
      metrics:
        enabled: false
