apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeseal
resources:
  - ./namespace.yaml
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.26.0/controller-norbac.yaml
