apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mage
  labels:
    app: mage
spec:
  selector:
    matchLabels:
      app: mage
  serviceName: mage
  template:
    metadata:
      labels:
        app: mage
    spec:
      hostNetwork: true
      containers:
        - name: mage-server
          image: mageai/mageai:latest
          ports:
            - containerPort: 6789
          volumeMounts:
            - name: mage-fs
              mountPath: /home/src
          env:
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: mage-fs
          persistentVolumeClaim:
            claimName: mage
