apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clickhouse-single
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: clickhouse-single
            port:
              number: 80
