apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: homelab
  namespace: clickhouse
spec:
  defaults:
    templates:
      podTemplate: pod-template
      serviceTemplate: svc-template
      dataVolumeClaimTemplate: data-volumeclaim-template

  configuration:
    clusters:
      - name: homelab
        layout:
          shardsCount: 1
          replicasCount: 1

    users:
      # HOW TO ADD NEW PASSWORD
      # cd clickhouse/20-clickhouse-installations
      # ../../_helpers.sh kubeseal_secret_create clickhouse-password <user> <password> 40-clickhouse-password-secret.yaml

      # User: default
      default/k8s_secret_password: clickhouse-password/default
      default/networks/ip:
        - 0.0.0.0/0

      # User: duyet
      duyet/k8s_secret_password: clickhouse-password/duyet
      duyet/networks/ip:
        - 0.0.0.0/0

      # User: monitoring
      monitoring/k8s_secret_password: clickhouse-password/monitoring
      monitoring/profile: readonly
      monitoring/networks/ip:
        - 10.1.0.0/16

    profiles:
      # Read data and Change settings queries are allowed
      readonly/readonly: '2'

    settings:
      compression/case/method: zstd
      disable_internal_dns_cache: 1

  templates:
    podTemplates:
      - name: pod-template
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:24.2
              env:
                - name: CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS
                  value: 'true'
                - name: CLICKHOUSE_INITDB_USER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse-password
                      key: default
              volumeMounts:
                - name: clickhouse-initdb-script
                  mountPath: /docker-entrypoint-initdb.d
          volumes:
            - name: clickhouse-initdb-script
              configMap:
                name: clickhouse-initdb-script

    serviceTemplates:
      - name: svc-template
        generateName: clickhouse-{chi}
        metadata:
          annotations:
            tailscale.com/expose: 'true'
            tailscale.com/hostname: 'clickhouse-cluster-homelab'
            tailscale.com/tags: 'tag:k8s,tag:minipc,tag:duet-ubuntu'
        spec:
          ports:
            - name: http
              port: 8123
            - name: tcp
              port: 9000
          type: ClusterIP

    volumeClaimTemplates:
      - name: data-volumeclaim-template
        spec:
          storageClassName: clickhouse-sc
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi
