apiVersion: v1
kind: Service
metadata:
  name: clickhouse-monitoring-homelab
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "clickhouse-monitoring-homelab"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: clickhouse-monitoring
    app.kubernetes.io/name: clickhouse-monitoring
  ports:
    - port: 3000
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 3000
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30001
