apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: clickhouse-monitoring
    includeCRDs: true
    releaseName: clickhouse-monitoring
    version: 0.1.2
    repo: https://duyet.github.io/charts
    valuesFile: values.yaml

resources:
  - ./10-clickhouse-monitoring-service-nodeport.yaml
