image:
  repository: ghcr.io/duyet/clickhouse-monitoring
  tag: main
  pullPolicy: Always

env:
  - name: CLICKHOUSE_HOST
    value: http://clickhouse-homelab:8123
  - name: CLICKHOUSE_USER
    value: monitoring
  - name: CLICKHOUSE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: clickhouse-password
        key: monitoring

service:
  type: ClusterIP
  port: 443
  portName: https

ingress:
  enabled: false
  className: tailscale
  hosts:
    - host: clickhouse-monitoring.homelab.duyet.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - clickhouse-monitoring.homelab.duyet.net
