env:
  - name: CLICKHOUSE_HOST
    value: http://clickhouse-single:8123
  - name: CLICKHOUSE_USER
    value: monitoring
  - name: CLICKHOUSE_PASSWORD
    value: monitoring

service:
  type: ClusterIP
  port: 443
  portName: https

ingress:
  enabled: true
  className: tailscale
  hosts:
    - host: clickhouse-monitoring.homelab.duyet.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - clickhouse-monitoring.homelab.duyet.net
